### ISSUE TITLE
Prepare Release 3.1.0

### ISSUE THREAD

**Issue by cortinico** [ChuckerTeam/chucker#194]
Let's use this issue to keep track of the things we need to do before releasing Chucker 3.1.0

If you have the feeling you have a feature or a fix that is worth being included in the upcoming release, please comment here asap.

- [x] Merge #182
- [x] Merge #193
- [x] Merge #190
- [x] Merge #189 
- [x] Investigate (and eventually fix) #192 
- [x] Update [CHANGELOG.md](/CHANGELOG.md)
- [x] Bump all the third party dependencies (Kotlin, Gradle, Support lib, etc.) #193
- [x] Prepare a migration document (probably not needed as there are no API change).
- [x] Update the screenshots on the README (probably already addressed in #156 #170)
- [x] Update the README to have examples of the newer API
- [x] Fix #197

**Comment by Aksi0m** [comment]
I do not see fix https://github.com/ChuckerTeam/chucker/issues/115 in the list so I am adding it here in hope it will be included in this release

**Comment by vbuberen** [comment]
@Aksi0m Thanks for reminding.
This list is just a set of things left to do, not already done. This is why you wasn't able to find that fix there.

We are going to abandon this practice of using issues for things left to do and switch to project boards with meaningful column names pretty soon to not confuse people.
